### ISSUE TITLE
ModuleNotFoundError: No module named 'moviepy.editor'

### ISSUE THREAD

**Issue by VQHieu1012** [anbit192/ASCII-Art-bad-apple#1]
I created a python virtual environment (3.11.0) and installed from requirements.txt. I have modified start.py to activate the virtual env before run the script: 

>cmd_command = f'cmd /c "mode con: cols={ASCII_OUTPUT_WIDTH + 2} lines={ASCII_OUTPUT_HEIGHT + 2} & Scripts\\activate & python {script_path}"'

but got some error 

> pygame 2.6.1 (SDL 2.28.4, Python 3.11.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "D:\ASCII-video\src\play_video.py", line 10, in <module>
    from moviepy.editor import VideoFileClip
ModuleNotFoundError: No module named 'moviepy.editor'

**Comment by anbit192** [comment]
Fixed! Please try again
